### PR TITLE
Syncing the latest changes for Release 1.5.0-rc

### PR DESCRIPTION
**Pull request by TusharKanekiDey**
Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

Syncing the upstream TVM on 10/13/2020.

### CODE REVIEW

**Comment by TusharKanekiDey** [comment]
@zhiics @trevor-m @kevinthesun

**Comment by trevor-m** [comment]
Can you update dmlc_commit_id file?

**Comment by TusharKanekiDey** [comment]
> Can you update dmlc_commit_id file?

It is been already updated to Commit ID 7d805b54d6adda82636d13bf7c46a2e9a933da5f in this revision.

**Comment by zhiics** [comment]
Yeah, I didn't see the change to dmlc_commit_id.txt either. Can you point out which commit changed that? Thanks.

**Comment by TusharKanekiDey** [comment]
> Yeah, I didn't see the change to dmlc_commit_id.txt either. Can you point out which commit changed that? Thanks.

https://github.com/TusharKanekiDey/tvm/commit/add07633aebab501fba257cc67df31481d0fe34f.

**Review by trevor-m — APPROVED** [review]

**Pull request merged**
