### PR TITLE
Support MXNet smooth_l1

### PR DESCRIPTION
**Pull request by haojin2**
...in both NNVM & Relay

### CODE REVIEW

**Review by yongwww — APPROVED** [review]
LGTM

**Comment by lokeshgupta1975** [comment]
This PR was never merged, the status is Closed, can someone say what happened with this PR?

**Comment by haojin2** [comment]
@lokeshgupta1975 similar changes with Relay version only merged into upstream TVM in https://github.com/apache/incubator-tvm/pull/2905.

**Comment by lokeshgupta1975** [comment]
@haojin2 Thank you !

**Pull request closed without merging**
